# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codethoughts.info" # the base hostname & protocol for your site
twitter_username: kui_sun
github_username:  puffsun

title: George's dream port
subtitle: Programming thoughts
author: George Sun
simple_search: http://google.com/search
description: Programming blog, notes, Tech blog, Ruby, Java
keywords: "Ruby, Java, Tech blog, Programming"


titlecase: true       # Converts page and post titles to titlecase

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# Build settings
markdown: kramdown
